<?php

namespace app\Shop\controllers;

use app\Main;
use app\Shop\models\ShopModel;

class Shop extends Main
{
	public function listView()
	{
		parent::listView(); // TODO: Change the autogenerated stub
		echo 'List View';
	}

	public function detailView()
	{
		parent::detailView(); // TODO: Change the autogenerated stub
		echo 'Detail View';
	}
}